export const languageList = [
  "Mandarin (entire branch)",
  "Spanish",
  "English",
  "Hindi[c]",
  "Arabic",
  "Portuguese",
  "Bengali",
  "Russian",
  "Japanese",
  "Punjabi",
  "German",
  "Javanese",
  "Wu (inc. Shanghainese)",
  "Malay (inc. Indonesian and Malaysian)",
  "Telugu",
  "Vietnamese",
  "Korean",
  "French",
  "Marathi",
  "Tamil",
  "Urdu",
  "Turkish",
  "Italian",
  "Yue (inc. Cantonese)",
  "Thai",
  "Gujarati",
  "Jin",
  "Southern Min (inc. Hokkien and Teochew)",
  "Persian",
  "Polish",
  "Pashto",
  "Kannada",
  "Xiang",
  "Malayalam",
  "Sundanese",
  "Hausa",
  "Odia (Oriya)",
  "Burmese",
  "Hakka",
  "Ukrainian",
  "Bhojpuri",
  "Tagalog (Filipino)",
  "Yoruba",
  "Maithili",
  "Uzbek",
  "Sindhi",
  "Amharic",
  "Fula",
  "Romanian",
  "Oromo",
  "Igbo",
  "Azerbaijani",
  "Awadhi",
  "Gan",
  "Cebuano (Visayan)",
  "Dutch",
  "Kurdish",
  "Serbo-Croatian",
  "Malagasy",
  "Saraiki",
  "Nepali",
  "Sinhala",
  "Chittagonian",
  "Zhuang",
  "Khmer",
  "Turkmen",
  "Assamese",
  "Madurese",
  "Somali",
  "Marwari",
  "Magahi",
  "Haryanvi",
  "Hungarian",
  "Chhattisgarhi",
  "Greek",
  "Chewa",
  "Deccan",
  "Akan",
  "Kazakh",
  "Northern Min[disputed – discuss]",
  "Sylheti",
  "Zulu",
  "Czech",
  "Kinyarwanda",
  "Dhundhari",
  "Haitian Creole",
  "Eastern Min (inc. Fuzhou dialect)",
  "Ilocano",
  "Quechua",
  "Kirundi",
  "Swedish",
  "Hmong",
  "Shona",
  "Uyghur",
  "Hiligaynon/Ilonggo (Visayan)",
  "Mossi",
  "Xhosa",
  "Belarusian",
  "Balochi",
  "Konkani",
];

export const RaceList = [
  "Arab",
  "White/Caucasian",
  "Black/Negroid",
  "American Indian",
  "South Asian",
  "East Asian",
  "Mongoloid",
  "Hispanic / Latino",
];

export const relegion = [
  "Judaism",
  "Christianity",
  "Islam",
  "Bahai",
  "Zoroastrianism",
  "Hinduism",
  "Jainism",
  "Buddhism",
  "Atheism",
  "Sikhism",
  "Taoism",
  "Confucianism",
  "Tenriism",
  "Vodu",
  "Shinto",
  "Taoism",
];

export const Star = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigashira",
  "Ardra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishaka",
  "Anurada",
  "Jyeshta",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishta",
  "Shatabhishak",
  "Purva Bhadrapada",
  "Uttara Bhadrapada",
  "Revati",
];

export const Visiblity = [
  "Public",
  "2nd cousins",
  "1st cousins",
  "Direct Family",
  "Descendants",
];

export const education_Level = [
  "None",
  "High School",
  "Secondary school",
  "Graduate",
  "Post graduate",
  "Doctorate",
];

export const educational_Area = [
  "Science/Tech",
  "Arts",
  "Humanities",
  "Social Science",
  "Medical",
  "Business/Commerce",
];

export const blood_group = ["A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-"];
export const smoking_habit = [
  "Never",
  "Experimented",
  "Occasional",
  "Regular",
  "Heavy",
];
export const physical_activity = ["Low", "Medium", "High"];
export const GoodQualities = [
  "Acceptance",
  "Assertiveness",
  "Authenticity",
  "Beauty",
  "Caring",
  "Cleanliness",
  "Commitment",
  "Compassion",
  "Confidence",
  "Consideration",
  "Contentment",
  "Cooperation",
  "Courage",
  "Creativity",
  "Detachment",
  "Determination",
  "Dignity",
  "Encouragement",
  "Enthusiasm",
  "Ethical",
  "Excellence",
  "Fairness",
  "Faith",
  "Flexibility",
  "Forgiveness",
  "Friendliness",
  "Generosity",
  "Gentleness",
  "Graciousness",
  "Gratitude",
  "Harmonious",
  "Helpfulness",
  "Honesty",
  "Honor",
  "Hope",
  "Humility",
  "Idealism",
  "Integrity",
  "Imaginative",
  "Joyfulness",
  "Justice",
  "Kindness",
  "Love",
  "Loyalty",
  "Moderation",
  "Modesty",
  "Optimistic",
  "Orderliness",
  "Passionate",
  "Patience",
  "Peace",
  "Perseverance",
  "Preparedness",
  "Purposefulness",
  "Reliability",
  "Respect",
  "Responsibility",
  "Reverence",
  "Self-discipline",
  "Service",
  "Sincerity",
  "Tact",
  "Temperate",
  "Tenacious",
  "Thankfulness",
  "Tolerance",
  "Trust",
  "Truthfulness",
  "Understanding",
  "Unity",
  "Visionary",
  "Wisdom",
  "Wonder",
];

export const WorstQualities = [
  "Anger",
  "Arrogance",
  "Bragging",
  "Cowardice",
  "Disloyalty",
  "Doubt",
  "Envy",
  "Greed",
  "Injustice",
  "Impatience",
  "Jealousy",
  "Recklessness",
  "Sloth",
  "Untrustworthiness",
  "Vanity",
  "Weakness",
  "Wrath",
];

export const FavouriteMusic = [
  "Blues",
  "Country",
  "Electronic",
  "Soft Rock",
  "Hard Rock",
  "Pop",
  "Indian Film",
  "Hip Hop",
  "Folk",
  "Jazz",
  "R&B / Soul",
  "Metal",
  "Punk",
  "Bhajan",
];
export const FavouriteSport = [
  "Archery",
  "Formula 1",
  "Artistic",
  "Gymnastics",
  "Athletics",
  "Badminton",
  "Basketball",
  "Beach Volleyball",
  "Cycling",
  "Boxing",
  "Canoeing",
  "Diving",
  "Horse Riding",
  "Fencing",
  "Football",
  "Wrestling",
  "Golf",
  "Martial Arts",
  "Hockey",
  "Marathon",
  "Swimming",
  "Mountain Bike",
  "Gymnastics",
  "Rowing",
  "Rugby",
  "Sailing",
  "Shooting",
  "Table Tennis",
  "Tennis",
  "Volleyball",
  "Water Polo",
  "Weightlifting",
  "Cricket",
  "Baseball",
  "Kabbadi",
  "Surfing",
  "Car Racing",
];

export const Relation = [
  "Mother",
  "Father",
  "Son",
  "Daughter",
  "Brother",
  "Sister",
  "Wife",
  "Husband",
];
